Attaching to jupyternotes_jupyter_1
[36mjupyter_1  |[0m Executing the command: jupyter notebook
[36mjupyter_1  |[0m [I 19:29:19.247 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[36mjupyter_1  |[0m [I 19:29:19.993 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
[36mjupyter_1  |[0m [I 19:29:19.993 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[36mjupyter_1  |[0m [I 19:29:19.997 NotebookApp] Serving notebooks from local directory: /home/jovyan
[36mjupyter_1  |[0m [I 19:29:19.997 NotebookApp] The Jupyter Notebook is running at:
[36mjupyter_1  |[0m [I 19:29:19.997 NotebookApp] http://4d422b43e9f0:8888/?token=deaf8223f26695b3d9b6973f83a91eb0d1a26cae99e1eb44
[36mjupyter_1  |[0m [I 19:29:19.997 NotebookApp]  or http://127.0.0.1:8888/?token=deaf8223f26695b3d9b6973f83a91eb0d1a26cae99e1eb44
[36mjupyter_1  |[0m [I 19:29:19.997 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[36mjupyter_1  |[0m [C 19:29:20.003 NotebookApp] 
[36mjupyter_1  |[0m     
[36mjupyter_1  |[0m     To access the notebook, open this file in a browser:
[36mjupyter_1  |[0m         file:///home/jovyan/.local/share/jupyter/runtime/nbserver-6-open.html
[36mjupyter_1  |[0m     Or copy and paste one of these URLs:
[36mjupyter_1  |[0m         http://4d422b43e9f0:8888/?token=deaf8223f26695b3d9b6973f83a91eb0d1a26cae99e1eb44
[36mjupyter_1  |[0m      or http://127.0.0.1:8888/?token=deaf8223f26695b3d9b6973f83a91eb0d1a26cae99e1eb44
[36mjupyter_1  |[0m [I 19:29:21.962 NotebookApp] 302 GET /?token=deaf8223f26695b3d9b6973f83a91eb0d1a26cae99e1eb44 (172.19.0.1) 0.70ms
[36mjupyter_1  |[0m [I 19:29:48.537 NotebookApp] Creating new notebook in /work
[36mjupyter_1  |[0m [I 19:29:48.554 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[36mjupyter_1  |[0m [I 19:29:49.196 NotebookApp] Kernel started: 96aeb9b4-10f9-4825-a4eb-5c06d012a41a
[36mjupyter_1  |[0m [I 19:29:51.825 NotebookApp] Starting buffering for 96aeb9b4-10f9-4825-a4eb-5c06d012a41a:5bb64f0451404c88b8c38fa6e3a08232
[36mjupyter_1  |[0m [I 19:29:55.310 NotebookApp] Creating new directory in /work
[36mjupyter_1  |[0m [I 19:31:03.929 NotebookApp] Creating new notebook in /work/ValueInvesting
[36mjupyter_1  |[0m [I 19:31:04.402 NotebookApp] Kernel started: 90237b12-5e01-4cd4-ab8c-b2defa7ccbcd
[36mjupyter_1  |[0m [I 19:33:04.416 NotebookApp] Saving file at /work/ValueInvesting/Untitled.ipynb
[36mjupyter_1  |[0m [I 19:54:35.901 NotebookApp] Saving file at /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:01:16.587 NotebookApp] Creating new directory in /work/ValueInvesting-TaewooKim
[36mjupyter_1  |[0m [W 20:03:04.416 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664169 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:03:04.417 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:03:04.417 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664169 (172.19.0.1) 2.50ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:03:04.432 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:03:04.446 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:03:04.449 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:03:04.449 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:03:04.450 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:03:04.450 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 19.83ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:05:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664170 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:05:04.410 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:05:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664170 (172.19.0.1) 2.34ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:05:04.420 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:05:04.436 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:05:04.437 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:05:04.437 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:05:04.438 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:05:04.438 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 18.90ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:07:04.412 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664171 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:07:04.412 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:07:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664171 (172.19.0.1) 2.29ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:07:04.423 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:07:04.430 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:07:04.430 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:07:04.431 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:07:04.431 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:07:04.431 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 9.64ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:09:04.405 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664172 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:09:04.406 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:09:04.406 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664172 (172.19.0.1) 0.92ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:09:04.412 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:09:04.416 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:09:04.416 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:09:04.416 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:09:04.417 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:09:04.417 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 5.44ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:11:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664173 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:11:04.411 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:11:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664173 (172.19.0.1) 2.25ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:11:04.421 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:11:04.438 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:11:04.438 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:11:04.439 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:11:04.440 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:11:04.440 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 19.90ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:13:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664174 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:13:04.411 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:13:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664174 (172.19.0.1) 2.28ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:13:04.423 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:13:04.429 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:13:04.429 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:13:04.430 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:13:04.431 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "713",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:13:04.431 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 9.33ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:15:04.409 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664175 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:15:04.410 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:15:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664175 (172.19.0.1) 2.25ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:15:04.419 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:15:04.433 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:15:04.434 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:15:04.434 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:15:04.435 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "783",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:15:04.435 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 17.13ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:17:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664176 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:17:04.410 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:17:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664176 (172.19.0.1) 2.27ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:17:04.420 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:17:04.434 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:17:04.434 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:17:04.435 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:17:04.436 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:17:04.436 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 16.66ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:19:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664177 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:19:04.411 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:19:04.412 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664177 (172.19.0.1) 2.28ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:19:04.422 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:19:04.437 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:19:04.438 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:19:04.439 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:19:04.440 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:19:04.440 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 18.92ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:21:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664178 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:21:04.411 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:21:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664178 (172.19.0.1) 2.31ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:21:04.420 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:21:04.435 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:21:04.436 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:21:04.436 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:21:04.437 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:21:04.437 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 18.79ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:23:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664179 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:23:04.414 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:23:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664179 (172.19.0.1) 1.31ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:23:04.423 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:23:04.428 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:23:04.428 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:23:04.428 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:23:04.429 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:23:04.429 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 6.82ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:25:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664180 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:25:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:25:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664180 (172.19.0.1) 2.42ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:25:04.422 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:25:04.437 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:25:04.437 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:25:04.437 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:25:04.438 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:25:04.438 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 16.50ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:27:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664181 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:27:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:27:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664181 (172.19.0.1) 1.55ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:27:04.419 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:27:04.434 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:27:04.435 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:27:04.435 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:27:04.436 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:27:04.436 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 17.82ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:29:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664182 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:29:04.414 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:29:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664182 (172.19.0.1) 2.35ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:29:04.424 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:29:04.439 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:29:04.440 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:29:04.440 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:29:04.441 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:29:04.441 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 18.84ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:31:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664183 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:31:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:31:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664183 (172.19.0.1) 2.33ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:31:04.422 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:31:04.428 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:31:04.429 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:31:04.429 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:31:04.430 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:31:04.430 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 8.86ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:33:04.410 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664184 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:33:04.410 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:33:04.411 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664184 (172.19.0.1) 1.53ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:33:04.418 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:33:04.434 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:33:04.435 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:33:04.435 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:33:04.436 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:33:04.436 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 18.78ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:35:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664185 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:35:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:35:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664185 (172.19.0.1) 2.22ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:35:04.423 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:35:04.428 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:35:04.429 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:35:04.429 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:35:04.430 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "834",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:35:04.430 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 8.53ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:35:53.245 NotebookApp] Uploading file to /work/ValueInvesting-TaewooKim/data/KrogersQ.csv
[36mjupyter_1  |[0m [W 20:37:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664186 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:37:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:37:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664186 (172.19.0.1) 2.20ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:37:04.422 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:37:04.426 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:37:04.427 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:37:04.428 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:37:04.428 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "973",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:37:04.429 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 7.41ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:39:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664187 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:39:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:39:04.414 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664187 (172.19.0.1) 2.29ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:39:04.423 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:39:04.426 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:39:04.427 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:39:04.427 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:39:04.428 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "1179",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:39:04.428 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 6.88ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:41:04.415 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664188 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:41:04.415 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:41:04.416 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664188 (172.19.0.1) 2.37ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:41:04.425 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:41:04.430 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:41:04.430 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:41:04.431 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:41:04.432 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "10051",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:41:04.432 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 8.13ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:41:20.115 NotebookApp] delete /work/ValueInvesting-TaewooKim/data/KrogersQ.csv
[36mjupyter_1  |[0m [I 20:41:40.059 NotebookApp] Uploading file to /work/ValueInvesting-TaewooKim/data/KrogersQ.csv
[36mjupyter_1  |[0m [W 20:43:04.415 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664189 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:43:04.416 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:43:04.416 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664189 (172.19.0.1) 2.62ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:43:04.428 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:43:04.432 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:43:04.433 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:43:04.434 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:43:04.435 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "7693",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:43:04.435 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 9.45ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:45:04.412 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664190 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:45:04.412 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:45:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664190 (172.19.0.1) 0.94ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:45:04.416 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:45:04.420 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:45:04.420 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:45:04.420 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:45:04.421 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "7693",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:45:04.421 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 5.41ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:46:10.688 NotebookApp] delete /work/ValueInvesting-TaewooKim/data/KrogersQ.csv
[36mjupyter_1  |[0m [I 20:46:34.384 NotebookApp] Uploading file to /work/ValueInvesting-TaewooKim/data/KrogersQ.csv
[36mjupyter_1  |[0m [W 20:47:04.412 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664191 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:47:04.413 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:47:04.413 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664191 (172.19.0.1) 1.61ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:47:04.420 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:47:04.433 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:47:04.433 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:47:04.433 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:47:04.434 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "8502",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:47:04.434 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 15.56ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:20.174 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664192 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:20.174 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:20.175 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664192 (172.19.0.1) 2.43ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:48:20.184 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:48:20.189 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:20.189 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:20.190 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:48:20.191 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15931",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:48:20.191 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 8.22ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:21.245 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664193 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:21.246 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:21.246 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664193 (172.19.0.1) 2.22ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:48:21.256 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:48:21.272 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:21.273 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:21.273 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:48:21.274 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15931",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:48:21.274 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 19.80ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:23.385 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664194 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:23.385 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:23.386 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664194 (172.19.0.1) 2.31ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:48:23.395 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:48:23.402 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:23.403 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:23.403 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:48:23.404 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15931",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:48:23.404 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 10.43ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:48:31.121 NotebookApp] Kernel started: 8d5f1355-1fca-4d1f-b978-4f7dcc881a56
[36mjupyter_1  |[0m [W 20:48:37.573 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664195 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:37.573 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:48:37.573 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664195 (172.19.0.1) 0.89ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:48:37.577 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:48:37.591 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:37.592 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:48:37.592 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:48:37.592 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15931",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:48:37.592 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 15.60ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:49:01.740 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:04.415 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664196 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:04.416 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:04.416 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664196 (172.19.0.1) 2.34ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:49:04.425 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:49:04.442 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:49:04.442 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:49:04.443 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:49:04.444 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15931",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:49:04.444 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 20.25ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:49:27.503 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:34.577 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664197 (172.19.0.1): No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:34.577 NotebookApp] No such file or directory: work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [W 20:49:34.578 NotebookApp] 404 GET /api/contents/work/ValueInvesting/Lesson1.ipynb?content=0&_=1594668664197 (172.19.0.1) 1.55ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:49:34.621 NotebookApp] Uploading file to /work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [E 20:49:34.623 NotebookApp] Error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m     Traceback (most recent call last):
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 467, in save
[36mjupyter_1  |[0m         self._save_notebook(os_path, nb)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 290, in _save_notebook
[36mjupyter_1  |[0m         with self.atomic_writing(os_path, encoding='utf-8') as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 210, in atomic_writing
[36mjupyter_1  |[0m         with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
[36mjupyter_1  |[0m         return next(self.gen)
[36mjupyter_1  |[0m       File "/opt/conda/lib/python3.7/site-packages/notebook/services/contents/fileio.py", line 105, in atomic_writing
[36mjupyter_1  |[0m         fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
[36mjupyter_1  |[0m     FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:49:34.623 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1): Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [W 20:49:34.623 NotebookApp] Unexpected error while saving file: work/ValueInvesting/Lesson1.ipynb [Errno 2] No such file or directory: '/home/jovyan/work/ValueInvesting/Lesson1.ipynb'
[36mjupyter_1  |[0m [E 20:49:34.624 NotebookApp] {
[36mjupyter_1  |[0m       "Host": "127.0.0.1:8888",
[36mjupyter_1  |[0m       "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
[36mjupyter_1  |[0m       "Accept": "application/json, text/javascript, */*; q=0.01",
[36mjupyter_1  |[0m       "Accept-Language": "en-US,en;q=0.5",
[36mjupyter_1  |[0m       "Accept-Encoding": "gzip, deflate",
[36mjupyter_1  |[0m       "Content-Type": "application/json",
[36mjupyter_1  |[0m       "X-Xsrftoken": "2|65266be7|89b567599923c6211d48ef474efec65e|1594668562",
[36mjupyter_1  |[0m       "X-Requested-With": "XMLHttpRequest",
[36mjupyter_1  |[0m       "Content-Length": "15845",
[36mjupyter_1  |[0m       "Origin": "http://127.0.0.1:8888",
[36mjupyter_1  |[0m       "Connection": "keep-alive",
[36mjupyter_1  |[0m       "Referer": "http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb",
[36mjupyter_1  |[0m       "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1594668562|23:username-127-0-0-1-8888|44:YTM1YTEzNjRiYjM1NGFhZmJjMjliODljZjExOWZmNzM=|b3ebce3d9879098f966dfc38d393e02eb51d138ec01d20f1ae5649844f0ab9a6\"; _xsrf=2|65266be7|89b567599923c6211d48ef474efec65e|1594668562"
[36mjupyter_1  |[0m     }
[36mjupyter_1  |[0m [E 20:49:34.624 NotebookApp] 500 PUT /api/contents/work/ValueInvesting/Lesson1.ipynb (172.19.0.1) 3.55ms referer=http://127.0.0.1:8888/notebooks/work/ValueInvesting/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:49:34.681 NotebookApp] Starting buffering for 90237b12-5e01-4cd4-ab8c-b2defa7ccbcd:ac5c4f03c97a47d889ef824273c770c4
[36mjupyter_1  |[0m [I 20:50:31.136 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:52:31.135 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:54:31.136 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 20:56:31.133 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:08:31.142 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:10:31.135 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:12:31.135 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:22:31.134 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:36:31.140 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:38:31.130 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:40:31.141 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:42:31.142 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:44:31.141 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:46:31.142 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:48:31.141 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:50:31.141 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:52:31.142 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 21:58:31.143 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:02:31.145 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:04:31.146 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:06:31.137 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:10:31.146 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:12:31.147 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:14:31.149 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:17:51.431 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:28:31.527 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:28:52.337 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:28:53.069 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1.ipynb
[36mjupyter_1  |[0m [I 22:29:41.253 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:50:32.352 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:52:32.513 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:53:58.747 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:54:32.511 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:56:32.505 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 22:58:32.513 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:00:32.514 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:02:32.502 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:04:32.512 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:06:32.512 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:10:32.513 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:12:32.513 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:14:32.504 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:16:32.508 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:17:41.439 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:17:42.079 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:18:03.994 NotebookApp] Saving file at /work/ValueInvesting-TaewooKim/Lesson1_UploadingDataFromSimFin.ipynb
[36mjupyter_1  |[0m [I 23:18:05.356 NotebookApp] Starting buffering for 8d5f1355-1fca-4d1f-b978-4f7dcc881a56:d7b8bf3622c14c6f8074ae916f5bc7cb
